version: '3.9'

services:
  database:
    container_name: database
    image: postgis/postgis:15-3.4-alpine  # Using PostGIS with Postgres 15 on Alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
   
volumes:
  redis-data:
