version: '3.7'

services:
  database:
    container_name: database
    image: tobi312/rpi-postgresql-postgis:15-3.4-alpine-arm
    volumes:
      - ./postgis:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
   
volumes:
  redis-data:
