swagger: "2.0"
info:
  title: Simple API
  version: "1.0"
paths:
  /hello:
    get:
      summary: Returns a greeting
      produces:
      - text/plain
      responses:
        200:
          description: greeting response
